#!/usr/bin/env python3

# Script Name:                  gendir
# Author:                       Your Name: Nick Van Noort
# Date of latest revision:      06/07/2023
# Purpose:                      Get dir tree

# Import libraries
import os

# Declaration of variables
directory_path = input("Please enter a directory path: ")

# Declaration of functions
def dir_subdir_files(path):
    for (root, dirs, files) in os.walk(path):
        print("Root:", root)
        print("Directories:", dirs)
        print("Files:", files)
        print("-------------------------------")

# Main
dir_subdir_files(directory_path)